### PR TITLE
4.0.1

### PR DESCRIPTION
**Pull request by ghost**
From changelog:
reduced variables usage
added more test coverage
replaced ternary operators with simple if statements
commented out puts statements
changed README from Markdown to RDoc format
added Gemnasium and Travis CI badges

If accepted, be sure to update TravisCI and Gemnasium references to your own account in the README.rdoc.

### CODE REVIEW

**Comment by antlypls** [comment]
@statique merge rumeme master branch into your pull request please.

**Comment by rafaelmagu** [comment]
Guys, what's the status on this? Please merge master branch as some of the changes have already been made. This gem needs to be version bumped as there is a stopping bug on 4.0.0 dealing with strip_invalid method setting all numbers to nil.

**Comment by antlypls** [comment]
@rafaelmagu what is your issue?

**Comment by rafaelmagu** [comment]
@antlypls The gem is still on 4.0.0, and that is coming with the wrong order of parameters on line 155 of sms_interface.rb. @scarver2 also submitted a patch for the same thing.

**Comment by antlypls** [comment]
@rafaelmagu isn't it fixed by PR #4?

**Comment by rafaelmagu** [comment]
It is, but the published gem hasn't been updated.

So doing 'gem install rumeme' still brings the buggy version to the system.

**Comment by antlypls** [comment]
@rafaelmagu oh, my bad. I've merged PR and published `rumeme-0.4.1` to rubygems. Take a look at that build, and let me know does it work for you.

**Comment by scarver2** [comment]
The tests and changelog need to be merged into this version.

**Comment by antlypls** [comment]
@scarver2 I've already did that. Thanks for your work on tests.

**Comment by scarver2** [comment]
Oops, I was looking at a cached page. 

Sorry I was not online yesterday and missed the party :) Thanks for accepting my pull request. 

Can you think of any other features that need to be added to this gem?

**Comment by antlypls** [comment]
There is an idea to mock requests to message media servers for tests, using `vcr` gem or something like that.
And please note, that project repo will be completely moved to https://github.com/antlypls/rumeme soon, since we don't use programmable account anymore.

**Comment by rafaelmagu** [comment]
I can confirm the latest gem (4.0.1) comes with the fixes. Thanks!

**Pull request merged**
